"""Add address table

Revision ID: e507abefc9e9
Revises: cedf7ad5f51f
Create Date: 2021-02-24 14:09:17.418934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e507abefc9e9'
down_revision = 'cedf7ad5f51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'address',
        sa.Column('address_Id', sa.INTEGER(), nullable=False),
        sa.Column('street', sa.VARCHAR(length=30), nullable=True),
        sa.Column('city', sa.VARCHAR(length=30), nullable=True),
        sa.Column('state', sa.VARCHAR(length=30), nullable=True),
        sa.Column('zip_code', sa.VARCHAR(length=30), nullable=True),
        sa.Column('state', sa.VARCHAR(length=30), nullable=True),
        sa.Column('name', sa.VARCHAR(length=30), nullable=True),
        sa.PrimaryKeyConstraint('address_Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
